export const userState = {
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    
    LOGOUT: 'USERS_LOGOUT',

    SIGN_START: 'SIGN_START',
    SIGN_SUCCESS: 'SIGN_SUCCESS',
    SIGN_FAIL: 'SIGN_FAIL'
};

